# Install and Import Libraries
Install Scikit-learn if not already installed and import necessary libraries such as pandas, numpy, and sklearn.

In [ ]:
# Install Scikit-learn
# Uncomment the line below if Scikit-learn is not installed
# !pip install scikit-learn

# Import libraries
import pandas as pd
import numpy as np
from sklearn import datasets

# Load Dataset
Load a sample dataset using Scikit-learn's built-in datasets or an external dataset using pandas.

In [4]:
# Load a sample dataset
from sklearn.datasets import load_iris

data = load_iris()
X, y = data.data, data.target
print("Features:", X[:5])
print("Labels:", y[:5])

Features: [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Labels: [0 0 0 0 0]


# Preprocess Data
Handle missing values, encode categorical variables, and scale numerical features using Scikit-learn preprocessing tools.

In [5]:
# Preprocess data
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("Scaled Features:", X_scaled[:5])

Scaled Features: [[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]]


# Split Dataset
Split the dataset into training and testing sets using train_test_split from Scikit-learn.

In [6]:
# Split the dataset
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
print("Training set size:", X_train.shape)
print("Test set size:", X_test.shape)

Training set size: (120, 4)
Test set size: (30, 4)


# Train a Model
Train a machine learning model (e.g., Linear Regression, Decision Tree, or Random Forest) using Scikit-learn.

In [7]:
# Train a model
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)
print("Model trained successfully.")

Model trained successfully.


# Evaluate the Model
Evaluate the model's performance using metrics such as accuracy, precision, recall, or mean squared error.

In [8]:
# Evaluate the model
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0


# Make Predictions
Use the trained model to make predictions on new or test data.

In [9]:
# Make predictions
new_data = X_test[:5]
predictions = model.predict(new_data)
print("Predictions:", predictions)

Predictions: [1 0 2 1 1]
